# Generated by Django 3.1.7 on 2021-07-02 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
