# Generated by Django 3.1.7 on 2021-07-02 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210702_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
